### ISSUE TITLE
Hi, I get this error when i try to run  python ducky-converter_P4wnP1-ALOA.py thru SSH, 

### ISSUE THREAD

**Issue by agavrilescu** [DuckyTools/DUCKY-CONVERTER-for-P4wnP1-A.L.O.A#1]
Traceback (most recent call last):
  File "ducky-converter_P4wnP1-ALOA.py", line 15, in <module>
    from modules.menu import MENU
  File "/root/DUCKY-CONVERTER-for-P4wnP1-A.L.O.A/modules/menu.py", line 2, in <m                                                                             odule>
    import pynput
  File "/usr/local/lib/python2.7/dist-packages/pynput/__init__.py", line 40, in                                                                              <module>
    from . import keyboard
  File "/usr/local/lib/python2.7/dist-packages/pynput/keyboard/__init__.py", lin                                                                             e 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/usr/local/lib/python2.7/dist-packages/pynput/keyboard/_xorg.py", line 3                                                                             9, in <module>
    from pynput._util.xorg import (
  File "/usr/local/lib/python2.7/dist-packages/pynput/_util/xorg.py", line 40, i                                                                             n <module>
    _check()
  File "/usr/local/lib/python2.7/dist-packages/pynput/_util/xorg.py", line 38, i                                                                             n _check
    display = Xlib.display.Display()
  File "/usr/local/lib/python2.7/dist-packages/Xlib/display.py", line 89, in __i                                                                             nit__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/display.py", line 71, in __i                                                                             nit__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 8                                                                             4, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/support/connect.py", line 73                                                                             , in get_display
    return mod.get_display(display)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/support/unix_connect.py", li                                                                             ne 76, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""

**Comment by himuura** [comment]
Plus one on this one. Same behaviour.

**Comment by himuura** [comment]
this happens with ssh session, i would believe that it would not happen with a normal setup (i.e. not running in headless mode)
