### ISSUE TITLE
 I get this error when i run ducky-converter_P4wnP1-ALOA.py file

### ISSUE THREAD

**Issue by lightingThunder** [DuckyTools/DUCKY-CONVERTER-for-P4wnP1-A.L.O.A#2]
ducky-converter_P4wnP1-ALOA.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp # need imp library
Traceback (most recent call last):
  File "ducky-converter_P4wnP1-ALOA.py", line 14, in <module>
    from modules.editor import editor
  File "C:\Users\Mahya\Desktop\DUCKY-CONVERTER-for-P4wnP1-A.L.O.A-master\modules\editor.py", line 18
    except KeyboardInterrupt:
    ^
IndentationError: expected an indented block

**Comment by SawyerTheNerd** [comment]
same here i have tried to add imp to the requirements but I can't find a working version
